In [1]:
import sys, os
sys.path.append(os.pardir)
import numpy as np
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient

In [54]:
class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2, 3)

    def predict(self, x):
        return np.dot(x, self.W)

    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)

        return loss

In [55]:
net = simpleNet()
print(net.W)

[[-0.39158737  0.52687021 -0.15926965]
 [ 1.88466042  0.47419858  0.78652705]]


In [56]:
x = np.array([0.6, 0.9])
p = net.predict(x)
print(p)

[1.46124195 0.74290085 0.61231255]


In [57]:
np.argmax(p)

0

In [58]:
t = np.array([0, 0, 1])
net.loss(x, t)

1.4988731895569767

In [67]:
print(x)
print(t)

# 損失関数
def f(W):
    return net.loss(x, t)

[0.6 0.9]
[0 0 1]


In [68]:
dW = numerical_gradient(f, net.W)
print(dW)

[[ 0.31324507  0.15272589 -0.46597096]
 [ 0.46986761  0.22908884 -0.69895645]]
