In [1]:
import numpy as np

In [10]:
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

print(X)
print(W1)
print(B1)

print(X.shape)
print(W1.shape)
print(B1.shape)

[1.  0.5]
[[0.1 0.3 0.5]
 [0.2 0.4 0.6]]
[0.1 0.2 0.3]
(2,)
(2, 3)
(3,)


In [12]:
A1 = np.dot(X, W1) + B1
A1

array([0.3, 0.7, 1.1])

In [13]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [14]:
Z1 = sigmoid(A1)
Z1

array([0.57444252, 0.66818777, 0.75026011])

In [15]:
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
B2 = np.array([0.1, 0.2])

In [18]:
A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)
Z2

array([0.62624937, 0.7710107 ])

In [19]:
def identity_function(x):
    return x

In [21]:
W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])

A3 = np.dot(Z2, W3) + B3
Y = identity_function(A3)
Y

array([0.31682708, 0.69627909])