In [63]:
import sys, os
sys.path.append(os.pardir)
from common.functions import *
from common.gradient import numerical_gradient

In [64]:
class TwoLayerNet:

    def __init__(self, input_size, hidden_size, output_size, weight_init_std=0.01):

        # 重みの初期化
        self.params = {}
        self.params["W1"] = weight_init_std * np.random.randn(input_size, hidden_size)

        self.params["b1"] = np.zeros(hidden_size)
        self.params["W2"] = weight_init_std * np.random.randn(hidden_size, output_size)

        self.params["b2"] = np.zeros(output_size)

    def predict(self, x):
        W1, W2 = self.params["W1"], self.params["W2"]
        b1, b2 = self.params["b1"], self.params["b2"]

        a1 = np.dot(x, W1) + b1
        z1 = sigmoid(a1)
        a2 = np.dot(z1, W2) + b2
        y = softmax(a2)

        return y

    # x: 入力データ, t: 教師データ
    def loss(self, x, t):
        y = self.predict(x)
        return  cross_entropy_error(y, t)

    def accuracy(self, x, t):
        y = self.predict(x)
        y = np.argmax(y, axis=1)
        t = np.argmax(t, axis=1)

        accuracy = np.sum(y == t) / float(x.shape[0])
        return accuracy

    # x: 入力データ, t: 教師データ
    def numerical_gradient(self, x, t):
        loss_W = lambda W: self.loss(x, t)

        grads = {}

        grads["W1"] = numerical_gradient(loss_W, self.params["W1"])
        grads["b1"] = numerical_gradient(loss_W, self.params["b1"])
        grads["W2"] = numerical_gradient(loss_W, self.params["W2"])
        grads["b2"] = numerical_gradient(loss_W, self.params["b2"])

        return grads

In [65]:
sum_lambda = lambda a, b: a + b
print(sum_lambda(1, 1))

2


In [66]:
net = TwoLayerNet(input_size=784, hidden_size=100, output_size=10)
print(net.params["W1"].shape)
print(net.params["b1"].shape)
print(net.params["W2"].shape)
print(net.params["b2"].shape)

(784, 100)
(100,)
(100, 10)
(10,)


In [67]:
net.params["W1"]

array([[ 0.00975008, -0.00426957,  0.00465399, ..., -0.00154216,
        -0.0107378 , -0.0200222 ],
       [-0.00237014, -0.00377611,  0.00510984, ..., -0.01146505,
         0.02307296,  0.02283988],
       [-0.00268046,  0.01045525, -0.0012282 , ...,  0.01536188,
         0.00943953, -0.00400469],
       ...,
       [-0.01369773, -0.0008016 , -0.0085613 , ...,  0.00577532,
        -0.01342032, -0.00896267],
       [-0.01175588,  0.00172924,  0.01070216, ...,  0.00701857,
         0.00343534, -0.00269984],
       [ 0.00721522,  0.00904907, -0.00025969, ..., -0.00333606,
        -0.00631409, -0.0077783 ]])

In [68]:
net.params["W2"]

array([[ 2.39466597e-03, -1.09049240e-02,  4.37716329e-03,
         7.38772096e-03,  4.72158673e-03, -2.57893719e-02,
        -1.93666510e-02, -1.06915554e-02,  4.63624445e-03,
        -1.54397423e-02],
       [-4.70366716e-03, -3.41781688e-03, -5.36024444e-03,
        -6.15087092e-05,  9.97975240e-03,  1.70619070e-02,
        -5.52028591e-03, -8.90705492e-03,  8.55078052e-03,
        -1.79602457e-02],
       [-6.63210686e-03, -4.16153812e-03,  9.85370265e-03,
         4.24894689e-03, -1.27603355e-02,  6.49382001e-03,
        -4.88454717e-03,  3.97136227e-03, -1.43415023e-02,
         3.74121156e-03],
       [-1.45486246e-02, -4.66415813e-03,  1.36497751e-02,
        -1.06994058e-02,  5.09750767e-03,  3.06955139e-03,
         8.73157311e-03, -2.56392257e-04, -1.78741266e-02,
        -2.30927602e-03],
       [-1.17437746e-02,  1.06139066e-02, -1.99256264e-02,
         1.07221376e-02,  2.91995961e-03, -6.77571265e-03,
        -2.46645459e-03, -2.08899241e-03,  8.66727906e-03,
        -5.

In [69]:
x = np.random.rand(100, 784) # ダミーの入力
y = net.predict(x)

params変数にはネットワークに必要なパラメータが全て格納されている。

In [70]:
y

array([[0.10061113, 0.09653007, 0.09762951, 0.107534  , 0.10332793,
        0.09887191, 0.1059161 , 0.09497613, 0.09584704, 0.09875618],
       [0.10031071, 0.09672172, 0.09760007, 0.10785048, 0.10341306,
        0.09838172, 0.10613995, 0.0945929 , 0.0964521 , 0.09853731],
       [0.10067552, 0.09665397, 0.09819364, 0.107774  , 0.10319698,
        0.09837961, 0.10590308, 0.09447333, 0.09623337, 0.09851649],
       [0.10044976, 0.09672557, 0.09766485, 0.10780205, 0.10337069,
        0.09923817, 0.10547698, 0.09441024, 0.09641251, 0.09844918],
       [0.10069382, 0.09708221, 0.09803993, 0.10735087, 0.10336112,
        0.09836725, 0.10559477, 0.09471968, 0.09653938, 0.09825096],
       [0.10043658, 0.09653731, 0.09785996, 0.10781091, 0.10335229,
        0.09885086, 0.10592308, 0.09445475, 0.09611373, 0.09866053],
       [0.10037047, 0.09652963, 0.09741572, 0.10775081, 0.10327845,
        0.09895116, 0.10576455, 0.09460236, 0.09636942, 0.09896742],
       [0.10046209, 0.09645211, 0.0975358

In [71]:
x = np.random.rand(100, 784)
t = np.random.rand(100, 10)

In [72]:
grads = net.numerical_gradient(x, t)

KeyboardInterrupt: 

In [ ]:
grads["W1"].shape