In [2]:
import numpy as np

In [3]:
x = np.array([1.0, 2.0, 3.0])
print(x)

[1. 2. 3.]


In [4]:
type(x)

numpy.ndarray

In [6]:
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [17]:
x = np.array([[21, 43], [43, 32], [54, 94]])
x = x.flatten()
print(x)
print(x[np.array([0, 2, 4])])
print(x[x>50])

[21 43 43 32 54 94]
[21 43 54]
[54 94]


In [18]:
x > 50

array([False, False, False, False,  True,  True])

array([43, 94, 32])